# Generated by Django 4.2.7 on 2023-11-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreatin',
            new_name='dateCreation',
        ),
    ]
